<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text17_text17</name>
   <tag></tag>
   <elementGuidId>6f48024b-12fc-45ae-8bfb-bfd6dc029b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34152e9e-6dfb-4240-80de-f8fcbfe83f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ca42b79-db55-4238-9b58-3c3b545fc4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text17</value>
      <webElementGuid>3441f25d-d48b-4505-9436-2c40de996a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text17&quot;)</value>
      <webElementGuid>0961ca1b-908a-439e-b7ab-95662038c601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text17']</value>
      <webElementGuid>831af4b8-5c81-4791-8efb-8048cc7dd28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[17]</value>
      <webElementGuid>f3ff7042-a350-4cd8-b564-8c89ad7a0141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text17']</value>
      <webElementGuid>b4722679-26fd-4fd1-beeb-ba4c066847c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
