<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text38_text38</name>
   <tag></tag>
   <elementGuidId>3c80947b-912e-4628-a67f-a167aff43f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text38']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text38</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70ac9bc3-05e5-4164-8ed1-356823ff1bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68df60d3-d8c9-48bf-85d5-d53eae79161e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text38</value>
      <webElementGuid>ec6abcc8-7c08-4536-a7ac-31f69fb648b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text38&quot;)</value>
      <webElementGuid>3653e910-e98a-4593-9a76-e01f331b8066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text38']</value>
      <webElementGuid>8d23dc81-1f5d-4a05-9c6a-b1d8dc2327b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[38]</value>
      <webElementGuid>96fea2d0-0837-4058-8ee3-a352307a2d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text38']</value>
      <webElementGuid>690d9203-748c-4afa-84b1-fd8ec11d6a26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
