<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text15_text15</name>
   <tag></tag>
   <elementGuidId>19237f49-9f92-42f0-b31e-daab20985dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text15']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text15</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>421dcf00-2b38-4a54-b7fc-208d1b15dc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28a0b210-b33b-4be4-b00f-74fe7f4fd023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text15</value>
      <webElementGuid>e21fcc16-2c7b-4a26-ac41-1e76d0180215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text15&quot;)</value>
      <webElementGuid>8265b96a-7bba-48fc-a507-d1ec1f3342f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text15']</value>
      <webElementGuid>bdb17125-ecd0-4819-bd62-8ad2ea7cc23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[15]</value>
      <webElementGuid>de01e6a9-ad63-45a3-8b43-7307a2198c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text15']</value>
      <webElementGuid>c38b3ff6-187e-412b-bb44-0a531bbe792c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
