<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text33_text33</name>
   <tag></tag>
   <elementGuidId>ee7e7dd2-49cd-4dea-96aa-69aa6a7b8e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text33']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a267c92-d94d-4562-93ba-9445d8ced0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b11e9f1-139d-4bc4-9a01-f0c7c174519b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text33</value>
      <webElementGuid>03548e74-33d4-4e2b-bd09-0e3fd43feeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text33&quot;)</value>
      <webElementGuid>48c52e49-57ba-43fc-9dba-b88488f1d07d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text33']</value>
      <webElementGuid>efc6d9ab-a3c5-42af-bdc5-180d8410937d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[33]</value>
      <webElementGuid>be0f9c67-31ff-4964-ba67-936aa892ffa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text33']</value>
      <webElementGuid>cbdc2bfc-a8ba-424d-89d9-4ef7cf700b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
