<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text34_text34</name>
   <tag></tag>
   <elementGuidId>999281fe-cd5e-4a61-ba93-84c8c70a1595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>325c05a2-075d-429f-b303-2c90c0ab0764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3da5af7d-233a-4285-84c4-1ad4a6b31fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text34</value>
      <webElementGuid>0946b5b9-1eb8-4107-822d-d064397865f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text34&quot;)</value>
      <webElementGuid>d4748531-baaa-468a-aedc-5f9222aa1f15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text34']</value>
      <webElementGuid>576a443b-ed79-4e6c-8af2-a46445362d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[34]</value>
      <webElementGuid>c34c9aa6-0199-448b-9aba-5e223273d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text34']</value>
      <webElementGuid>72c8a91a-31a8-4fc0-b456-ae9c3234494f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
