<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text19_text19</name>
   <tag></tag>
   <elementGuidId>9e412bb1-0414-4023-bd4e-021a9a3d6f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9897c0e4-1113-4fea-bf1b-4fabef64762e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3f23782-11a3-45d3-b807-a403e97092e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text19</value>
      <webElementGuid>522cc5c5-3ca6-479d-acf7-a0942ed7d851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text19&quot;)</value>
      <webElementGuid>0f046923-73ee-44c8-b7b3-aa5470dc6f30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text19']</value>
      <webElementGuid>8fe87f53-36ec-4af1-a2e2-af0404971f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[19]</value>
      <webElementGuid>13f180bb-7f6c-42db-b965-13d18c2bab1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text19']</value>
      <webElementGuid>f7c6f3e9-6ee0-46c5-8e8b-110e8c7e974f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
