<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text20_text20</name>
   <tag></tag>
   <elementGuidId>eb6e5b41-c0f7-4949-97b7-428b256c22a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text20']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>176ce1bc-31ca-4830-ae70-7c5ed22e427a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b0b6718-4cf0-4841-b42a-3c9bd8263762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text20</value>
      <webElementGuid>5a406c50-4a51-4dfe-a685-862f21142d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text20&quot;)</value>
      <webElementGuid>4931207a-2b40-40e1-9b9e-5ca8f28fe5ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text20']</value>
      <webElementGuid>58b2a766-3b36-4445-a60a-d969438b39b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[20]</value>
      <webElementGuid>28347e86-aadd-41ff-9cf9-7d426fe9537f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text20']</value>
      <webElementGuid>fadf7e99-9322-4d5d-bb8b-7e3e543f169a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
