<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text10_checkbox1</name>
   <tag></tag>
   <elementGuidId>dbf98019-8ba3-487f-8324-61ec0c626caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d295643-29f5-4831-bff7-22f2dba25c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fb0dd982-b8fa-41d3-a2ec-1299ddb7ed98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox1</value>
      <webElementGuid>de77f3ec-c167-4aa5-bee8-568eb4858f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox1</value>
      <webElementGuid>9fc69492-e13e-44fb-a9c7-e7cb2fd2befd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox1&quot;)</value>
      <webElementGuid>13c49cd4-2198-49c7-87c0-95875395eb62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox1']</value>
      <webElementGuid>c9e3dc4e-f3a8-45f3-ba12-9668a45f1f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>acdc6f70-d597-4f8b-beef-ff8b5154cb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox1']</value>
      <webElementGuid>5c9d8dbb-5a2f-471f-9151-b1923b0cb8be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
