<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_value1          value2          valu_9f7bd8_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>610627e4-075c-4ffd-ae82-9c00bd71a951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#option7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7a132b13-c03f-48a3-969b-a738feca4c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option7</value>
      <webElementGuid>0e6d312d-84ae-4123-97dd-6842937b2cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          value1
          value2
          value3
          value4
        </value>
      <webElementGuid>c7216a24-b9a7-4a73-b391-7e0ac313aba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option7&quot;)</value>
      <webElementGuid>62f3e0b3-1247-4e99-9636-cc730392166a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option7']</value>
      <webElementGuid>90ab2316-2aa8-4e24-99bd-1b7c972f600e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option7:'])[1]/following::select[1]</value>
      <webElementGuid>c84b9a64-5469-4964-828d-f87102201fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option6:'])[1]/following::select[2]</value>
      <webElementGuid>38ad8bbc-5c12-4f09-928c-9a22cd1bc475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option8:'])[1]/preceding::select[1]</value>
      <webElementGuid>b61154ca-aa90-4d38-b205-59b2affe4a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option9:'])[1]/preceding::select[2]</value>
      <webElementGuid>0ef7ab61-f05d-4496-a850-967ea3b70096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[7]</value>
      <webElementGuid>65483016-1896-47ec-b506-3c82eecc0892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option7' and (text() = '
          value1
          value2
          value3
          value4
        ' or . = '
          value1
          value2
          value3
          value4
        ')]</value>
      <webElementGuid>2f05d078-cb78-457c-848f-931d36f7707b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
